# Generated by Django 5.0.2 on 2024-04-06 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_companyprofile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'ordering': ['-pk']},
        ),
    ]
