# Generated by Django 5.0.2 on 2024-04-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_companyprofile_options'),
        ('jobs', '0004_alter_job_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='skills',
            field=models.ManyToManyField(related_name='technologies', to='jobs.skills', verbose_name='Technologies'),
        ),
    ]
