# Generated by Django 5.0.2 on 2024-03-31 19:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_closed',
        ),
        migrations.AddField(
            model_name='job',
            name='benefits',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
