# Generated by Django 5.0.2 on 2024-03-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('jobseekers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='skills',
            field=models.ManyToManyField(related_name='skills', to='jobs.skills'),
        ),
    ]
