# Generated by Django 5.0.2 on 2024-04-06 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0002_alter_jobseeker_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobseeker',
            options={'ordering': ['-pk']},
        ),
    ]
